### PR TITLE
Replace tilde with HOME

### PR DESCRIPTION
**Pull request by flyingcakes85**
#23

### CODE REVIEW

**Review by killajoe — COMMENTED** [review]
Not sure would need to test but Pictures is language specific and will most likely not work if you are using non en language..

**Comment by flyingcakes85** [comment]
@killajoe 

Then we could ask xdg itself about which folder is right :wink: 

```
xdg-user-dir PICTURES
```

Could please you check if its ok? I'm using en_US so it works for me anyways.

**Review by killajoe — COMMENTED** [review]
just tried that in VM but keybindings are not really a thing you can check nicely in VirtualBox.. seems screwed but could be also that the keyboard is not parsed correctly into the VM..

**Comment by killajoe** [comment]
i can do a real hardware install later..

**Comment by flyingcakes85** [comment]
@killajoe 

I meant to say that you should run `xdg-user-dir PICTURES` and share output. Don't need a virtual box install. Also, keybindings indeed don't work well in virbual machine.

**Comment by killajoe** [comment]
seems to do the trick see:

**Comment by flyingcakes85** [comment]
Ah thanks; means the command does indeed work. I'll make a new pull request with the xdg command used.

**Pull request closed without merging**
